name: 'Fetch GitHub Action Queue'
description: 'Fetch Github Action queues and pending workflows for repository for statistics'
author: 'TobKed'
inputs:
  token:
    description: 'The GITHUB_TOKEN secret of the repository'
    required: true
  repository:
    description: 'Repository'
    required: true
outputs:
  workflowRuns:
    description: JSON with array payload of not finished workflow runs
  nrOfWorkflowRuns:
    description: Number of not finished workflow runs
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'play'
  color: 'blue'
